import { InventoryProduct } from "../types/inventory.types";

export const MOCK_PRODUCTS: InventoryProduct[] = [
  {
    id: "1",
    title: "Hand-carved Walnut Spoon",
    price: 54,
    status: "active",
    category: "HAND-CARVED",
    stockCount: 12,
    images: [{ url: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?q=80&w=2070&auto=format&fit=crop", publicId: "1" }],
    description: "A beautifully hand-carved spoon made from sustainably sourced walnut wood.",
    tags: ["wood", "hand-carved", "spoon"],
    artisanAnalysis: "The wood grain is exquisite and shows great craftsmanship.",
    createdAt: new Date(),
  },
  {
    id: "2",
    title: "Desert Ochre Planter",
    price: 82,
    status: "active",
    category: "CERAMIC",
    stockCount: 2,
    images: [{ url: "https://images.unsplash.com/photo-1616401784845-180882ba9ba8?q=80&w=2070&auto=format&fit=crop", publicId: "2" }],
    description: "A minimalist ceramic planter with a warm ochre glaze inspired by the desert.",
    tags: ["ceramic", "planter", "desert"],
    artisanAnalysis: "The glaze consistency is perfect.",
    createdAt: new Date(),
  },
  {
    id: "3",
    title: "Indigo Mist Mug",
    price: 32,
    status: "active",
    category: "CERAMIC",
    stockCount: 24,
    images: [{ url: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?q=80&w=2070&auto=format&fit=crop", publicId: "3" }],
    description: "A cozy ceramic mug with a deep indigo blue finish.",
    tags: ["ceramic", "mug", "indigo"],
    artisanAnalysis: "The handle is ergonomically designed for a perfect grip.",
    createdAt: new Date(),
  },
  {
    id: "4",
    title: "Heirloom Linen Set",
    price: 120,
    status: "draft",
    category: "ECO-CERTIFIED",
    stockCount: 0,
    images: [{ url: "https://images.unsplash.com/photo-1616131303221-7b16259d1df9?q=80&w=1974&auto=format&fit=crop", publicId: "4" }],
    description: "A luxurious set of heirloom-quality linen for your home.",
    tags: ["linen", "eco-certified", "home"],
    artisanAnalysis: "The weave is tight and durable.",
    createdAt: new Date(),
  },
  {
    id: "5",
    title: "Oak Cutting Board",
    price: 45,
    status: "out-of-stock",
    category: "WOODWORK",
    stockCount: 0,
    images: [{ url: "https://images.unsplash.com/photo-1594918352623-a1299e52e58e?q=80&w=2070&auto=format&fit=crop", publicId: "5" }],
    description: "A sturdy cutting board crafted from solid white oak.",
    tags: ["wood", "oak", "cutting board"],
    artisanAnalysis: "The wood is perfectly seasoned and oiled.",
    createdAt: new Date(),
  },
  // Add more to test pagination
  ...Array.from({ length: 15 }).map((_, i) => ({
    id: `mock-${i}`,
    title: `Artisan Product ${i + 6}`,
    price: Math.floor(Math.random() * 100) + 20,
    status: ["active", "draft", "out-of-stock"][i % 3],
    category: i % 2 === 0 ? "TEXTILE" : "POTTERY",
    stockCount: i % 3 === 0 ? 0 : Math.floor(Math.random() * 20) + 1,
    images: [{ url: "https://images.unsplash.com/photo-1506806732259-39c2d4468677?q=80&w=2070&auto=format&fit=crop", publicId: `mock-img-${i}` }],
    description: "A unique artisan creation from our collection.",
    tags: ["artisan", "handmade"],
    artisanAnalysis: "Shows authentic handmade character.",
    createdAt: new Date(),
  })),
];
